#
# File: vagrant.env.yml
# Description: Deploy vagrant environment.
#
---

-   name: "Deploy vagrant environment"
    hosts: "*"

# Run playbooks
-   include: playbooks/swap.yml env_vars="['../vars/vagrant.env.yml']"
-   include: playbooks/git.yml
-   include: playbooks/ssh.yml
-   include: playbooks/ntp.yml
-   include: playbooks/nginx.yml
-   include: playbooks/nginx-vagrant.yml env_vars="['../vars/vagrant.env.yml', '../vars/default.env.yml']"
-   include: playbooks/php7.yml
-   include: playbooks/composer.yml
-   include: playbooks/redis.yml
-   include: playbooks/beanstalkd.yml
-   include: playbooks/mongodb.yml
-   include: playbooks/nodejs.yml
-   include: playbooks/java8.yml
-   include: playbooks/elasticsearch.yml
