#
# File: vagrant.env.yml
# Description: Variables for vagrant environment.
#
---

# Environment variables
app_user: 'vagrant'
app_env: 'dev'

swapfile_mem: '1024M'

# Application default variables
app_nginx_vhosts:
  - { src: '../templates/nginx/sites-available/api-vagrant.conf.j2', dest: '/etc/nginx/sites-available/api-vagrant.conf', link: 'api-vagrant.conf' }
  - { src: '../templates/nginx/sites-available/doc-api-vagrant.conf.j2', dest: '/etc/nginx/sites-available/doc-api-vagrant.conf', link: 'doc-api-vagrant.conf' }
  - { src: '../templates/nginx/sites-available/eshq-vagrant.conf.j2', dest: '/etc/nginx/sites-available/eshq-vagrant.conf', link: 'eshq-vagrant.conf' }
  - { src: '../templates/nginx/sites-available/rockmongo-vagrant.conf.j2', dest: '/etc/nginx/sites-available/rockmongo-vagrant.conf', link: 'rockmongo-vagrant.conf' }
  - { src: '../templates/nginx/sites-available/odeon-vagrant.conf.j2', dest: '/etc/nginx/sites-available/admin-vagrant.conf', link: 'admin-vagrant.conf' }

app_backend_dir: '/var/www/odeon-backend'
app_frontend_dir: '/var/www/odeon-frontend'
app_doc_dir: '/var/www/odeon-frontend-doc'

# Elasticsearch
elasticsearch_index: 'odeon'
elasticsearch_host: 'localhost'
elasticsearch_port: '9200'
